theme = "iceberg-dark"

hide-mouse-cursor-when-typing = true

env-vars = ["TERM=xterm-256color"]

[fonts]
size = 28
hinting = true

[fonts.regular]
family = "Iosevka"
style = "normal"
weight = 400

[fonts.bold]
family = "Iosevka"
style = "normal"
weight = 800

[fonts.italic]
family = "Iosevka"
style = "italic"
weight = 400

[fonts.bold-italic]
family = "Iosevka"
style = "italic"
weight = 800

[navigation]
mode = "plain" 

[renderer]
backend = "Vulkan"
disable-renderer-when-unfocused = true

[cursor]
shape = "underline"
blinking = false

[editor]
program = "hx"
args = []
